### ISSUE TITLE
need date picker

### ISSUE THREAD

**Issue by okool** [AnnaSearl/annar#25]
有没有日历,日期,时间选择器.
手写,计算日期都算疯了,日历格子排版老不对.

**Comment by AnnaSearl** [comment]
看来大家都需要DatePicker啊，把这个组件的排期提前吧

**Comment by Findiqam** [comment]
期待 anna remax ui 的 datepicker ，真的很喜欢这个风格的 ui 。

**Comment by AnnaSearl** [comment]
anna-next 已经有DatePicker，不过next版本是破坏性的更新，如果要使用的话，请谨慎升级哦

**Comment by produmpling** [comment]
你们用 date-picker 组件在 微信里面卡么？我感觉比较卡

**Comment by 269378737** [comment]
> 你们用 date-picker 组件在 微信里面卡么？我感觉比较卡

我也觉得比较卡，不流畅，连官网的demo也是
