### ISSUE TITLE
swiper报错

### ISSUE THREAD

**Issue by shamerKill** [AnnaSearl/annar#48]
swiper在小程序里手动华滑动的时候会报错，handleTouchEnd函数里e.changedTouches[0]找不到
报错信息:
MiniProgramError
Cannot read property 'pageX' of undefined
TypeError: Cannot read property 'pageX' of undefined

解决方法：
将  var touch = e.changedTouches[0]; 改为
var touch = e.changedTouches[0] || e.nativeEvent.changedTouches[0];

**Comment by Jairwin-L** [comment]
请问这个解决方法是写在哪里？

**Comment by konglinlin** [comment]
我提交的有pr，就是这个https://github.com/AnnaSearl/annar/pull/49

**Comment by AnnaSearl** [comment]
在2.0.6中已解决

**Comment by qhdxwdm** [comment]
> 在2.0.6中已解决
我拉的工程是2.0.7的，但是swiper组件还是报错
![image](https://user-images.githubusercontent.com/48936860/99934894-50dff480-2d9a-11eb-977c-ff83df6d4dac.png)
不知道这个怎么解决
