### ISSUE TITLE
form表单 如何做联动

### ISSUE THREAD

**Issue by PlutoCA** [AnnaSearl/annar#51]
![image](https://user-images.githubusercontent.com/31099607/100519939-15985800-31d6-11eb-8456-dfe3ba87f411.png)

不能给表单元素绑定value和onchange的话，那有木有什么好办法可以做到联动呢

🤔️

**Comment by PlutoCA** [comment]
目前想了一个笨办法用小程序节点`createSelectorQuery`去获取这个元素的value属性值  😅

**Comment by YongcunPan** [comment]
是的，迫切需要一个shouldUpdate的属性

**Comment by AnnaSearl** [comment]
最新的Form 已经解决了这个问题哦
