### ISSUE TITLE
Swiper组件中Swiper.Item组件位置异常

### ISSUE THREAD

**Issue by rexjz** [AnnaSearl/annar#53]
### 测试Swiper组件时，Sipwe.Item的位置位于屏幕之外
js:
```
import * as React from "react";
import {Image, View} from 'remax/wechat';
import styles from './clubs.css';
import {Swiper as AnnarSwiper} from "annar";


export default class ClubsPage extends React.Component {
    render(){
        return(
            <View className={styles.clubsPage}>
                <AnnarSwiper autoplay = 'true' autoplayInterval = '3000'
                             height='300px'
                             size = 'middle'
                             showIndicators='true'
                             shape = 'sharp'
                >
                    <AnnarSwiper.Item className={styles.SwiperItem}>
                        <Image style = 'height:100%;width:100%'src ="/images/test.png"/>
                    </AnnarSwiper.Item>
                    <AnnarSwiper.Item >
                        <Image style = 'height:100%;width:100%' src ="/images/test.png"/>
                    </AnnarSwiper.Item>
                </AnnarSwiper>
            </View>
        )
    }
}
```
css:
```
.clubsPage{
    background-color: #8FCAF7;
}

.SwiperItem{
    height: 100px;
    width:300px;
}
```
渲染后只有外框:

![屏幕截图 2020-12-02 111343](https://user-images.githubusercontent.com/54502639/100823616-7d2cfc80-348f-11eb-9025-0e06e0bb576b.png)
观察页面wxmal排错时发现Swiper.Item位于屏幕之外:
![屏幕截图 2020-12-02 111616](https://user-images.githubusercontent.com/54502639/100825365-d0ed1500-3492-11eb-91ac-9e298d82fae5.png)

将异常的属性强行改成100px后Swiper.Item回到屏幕内部，但是排列仍有异常，不符合横向轮播的排列
![屏幕截图 2020-12-02 111233_2](https://user-images.githubusercontent.com/54502639/100824008-4e635600-3490-11eb-984e-71ec8de57b07.png)
![屏幕截图 2020-12-02 111233_1](https://user-images.githubusercontent.com/54502639/100824004-4c00fc00-3490-11eb-827b-bf1c1a03bfb7.png)

**Comment by AnnaSearl** [comment]
不需要给SwiperItem设置宽度哦，SwiperItem会自动填满父元素（Swiper）的哦
