### ISSUE TITLE
似乎这个库目前无法正常使用?

### ISSUE THREAD

**Issue by BenLampson** [AnnaSearl/annar#55]
![image](https://user-images.githubusercontent.com/15414750/101231230-c4f89180-36e4-11eb-9039-46efc2085b8a.png)
![image](https://user-images.githubusercontent.com/15414750/101231237-cd50cc80-36e4-11eb-9c12-1d7b16430a45.png)
目前这个row,grid之类的布局组件是完全无法使用啊.
尝试去掉外层的view也无法正常显示诶?
有没有什么解决方案?
![image](https://user-images.githubusercontent.com/15414750/101231247-e35e8d00-36e4-11eb-9031-d0129182b48b.png)
就看官方的DEMO似乎也没有用到row跟grid,而是封装了一个叫做Frame与block的组件.
所以我要使用这个库该如何操作?除了组件样式外布局完全自己编码吗?

**Comment by AnnaSearl** [comment]
row和grid有文档的哦，在layout类目下
