### ISSUE TITLE
Tabs样式问题

### ISSUE THREAD

**Issue by BenLampson** [AnnaSearl/annar#60]
不知道为什么,我的TABS的标题点击时始终会有一个背景的样式(官方DEMO没有,仅限官网没有)
我实机测试也有...
![asd](https://user-images.githubusercontent.com/15414750/102239673-11886c00-3f32-11eb-8076-d39e98a0e2d3.gif)

**Comment by BenLampson** [comment]
已经处理,小程序自带的一个问题.

**Comment by lihaooo** [comment]
@BenLampson 
请问一下是怎么解决的啊？我也碰到了

**Comment by douxc** [comment]
@lihaooo 去掉 ```cursor:pointer```

**Comment by lihaooo** [comment]
非常感谢
.anna-tabs-slider-title {
 cursor: none;
}
完美解决
在 2021年2月6日 +0800 PM9:35，douxc <notifications@github.com>，写道：
