### ISSUE TITLE
Steps组件的current以及status在direction=vertical时不生效

### ISSUE THREAD

**Issue by Vicfeel** [AnnaSearl/annar#78]
"dependencies": {
        "annar": "^2.0.9",
        "react": "^16.14.0",
        "remax": "^2.11.6"
    }

**Comment by Vicfeel** [comment]
看到这里已经修复了
https://github.com/AnnaSearl/annar/commit/720f42c0a9614a7dfda8422b6211e0ca7248a02a

求问新版本发布时间？

**Comment by AnnaSearl** [comment]
2.1.0 已经修复了哦
