### ISSUE TITLE
ImageUpload组件IOS上选择图片预览时，无论点击哪张都显示第一张的，安卓正常

### ISSUE THREAD

**Issue by gao525280067** [AnnaSearl/annar#87]
如题，点击第二张，第三张都显示第一张的图片
![image](https://user-images.githubusercontent.com/25193804/120269068-a52fd800-c2d9-11eb-8b39-c89f3fc6f5e8.png)

**Comment by gao525280067** [comment]
微信端小程序，这么修复，多平台的未测，等待修复
![image](https://user-images.githubusercontent.com/25193804/120416860-6b6dd880-c390-11eb-99f0-425fcfda759a.png)

**Comment by produmpling** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.previewImage.html#%E5%8F%82%E6%95%B0  previewImage 官方接口有修改
